
donnees = [
	['0', {
		'age': '45',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '110',
		'chol': '264',
		'fbs': '0',
		'restecg': '1',
		'thalach': '132',
		'exang': '0',
		'oldpeak': '1.2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '62',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '128',
		'chol': '208',
		'fbs': '1',
		'restecg': '0',
		'thalach': '140',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '71',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '160',
		'chol': '302',
		'fbs': '0',
		'restecg': '1',
		'thalach': '162',
		'exang': '0',
		'oldpeak': '0.4',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '70',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '156',
		'chol': '245',
		'fbs': '0',
		'restecg': '0',
		'thalach': '143',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '71',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '110',
		'chol': '265',
		'fbs': '1',
		'restecg': '0',
		'thalach': '130',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '29',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '130',
		'chol': '204',
		'fbs': '0',
		'restecg': '0',
		'thalach': '202',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '41',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '105',
		'chol': '198',
		'fbs': '0',
		'restecg': '1',
		'thalach': '168',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '47',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '112',
		'chol': '204',
		'fbs': '0',
		'restecg': '1',
		'thalach': '143',
		'exang': '0',
		'oldpeak': '0.1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '52',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '120',
		'chol': '325',
		'fbs': '0',
		'restecg': '1',
		'thalach': '172',
		'exang': '0',
		'oldpeak': '0.2',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '55',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '135',
		'chol': '250',
		'fbs': '0',
		'restecg': '0',
		'thalach': '161',
		'exang': '0',
		'oldpeak': '1.4',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '54',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '108',
		'chol': '309',
		'fbs': '0',
		'restecg': '1',
		'thalach': '156',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '53',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '138',
		'chol': '234',
		'fbs': '0',
		'restecg': '0',
		'thalach': '160',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '39',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '138',
		'chol': '220',
		'fbs': '0',
		'restecg': '1',
		'thalach': '152',
		'exang': '0',
		'oldpeak': '0',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '57',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '154',
		'chol': '232',
		'fbs': '0',
		'restecg': '0',
		'thalach': '164',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '57',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '140',
		'chol': '241',
		'fbs': '0',
		'restecg': '1',
		'thalach': '123',
		'exang': '1',
		'oldpeak': '0.2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '54',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '108',
		'chol': '267',
		'fbs': '0',
		'restecg': '0',
		'thalach': '167',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '48',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '124',
		'chol': '255',
		'fbs': '1',
		'restecg': '1',
		'thalach': '175',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '61',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '145',
		'chol': '307',
		'fbs': '0',
		'restecg': '0',
		'thalach': '146',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '51',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '94',
		'chol': '227',
		'fbs': '0',
		'restecg': '1',
		'thalach': '154',
		'exang': '1',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '51',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '125',
		'chol': '245',
		'fbs': '1',
		'restecg': '0',
		'thalach': '166',
		'exang': '0',
		'oldpeak': '2.4',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '56',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '120',
		'chol': '236',
		'fbs': '0',
		'restecg': '1',
		'thalach': '178',
		'exang': '0',
		'oldpeak': '0.8',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '54',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '150',
		'chol': '232',
		'fbs': '0',
		'restecg': '0',
		'thalach': '165',
		'exang': '0',
		'oldpeak': '1.6',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '48',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '130',
		'chol': '275',
		'fbs': '0',
		'restecg': '1',
		'thalach': '139',
		'exang': '0',
		'oldpeak': '0.2',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '54',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '120',
		'chol': '258',
		'fbs': '0',
		'restecg': '0',
		'thalach': '147',
		'exang': '0',
		'oldpeak': '0.4',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '50',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '140',
		'chol': '233',
		'fbs': '0',
		'restecg': '1',
		'thalach': '163',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '47',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '138',
		'chol': '257',
		'fbs': '0',
		'restecg': '0',
		'thalach': '156',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '44',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '108',
		'chol': '141',
		'fbs': '0',
		'restecg': '1',
		'thalach': '175',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '51',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '120',
		'chol': '295',
		'fbs': '0',
		'restecg': '0',
		'thalach': '157',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '45',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '104',
		'chol': '208',
		'fbs': '0',
		'restecg': '0',
		'thalach': '148',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '66',
		'sex': '0' ,
		'cp': '3',
		'trestbps': '150',
		'chol': '226',
		'fbs': '0',
		'restecg': '1',
		'thalach': '114',
		'exang': '0',
		'oldpeak': '2.6',
		'slope': '0',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '41',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '110',
		'chol': '235',
		'fbs': '0',
		'restecg': '1',
		'thalach': '153',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '51',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '140',
		'chol': '308',
		'fbs': '0',
		'restecg': '0',
		'thalach': '142',
		'exang': '0',
		'oldpeak': '1.5',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '61',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '150',
		'chol': '243',
		'fbs': '1',
		'restecg': '1',
		'thalach': '137',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '45',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '138',
		'chol': '236',
		'fbs': '0',
		'restecg': '0',
		'thalach': '152',
		'exang': '1',
		'oldpeak': '0.2',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '44',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '130',
		'chol': '233',
		'fbs': '0',
		'restecg': '1',
		'thalach': '179',
		'exang': '1',
		'oldpeak': '0.4',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '44',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '118',
		'chol': '242',
		'fbs': '0',
		'restecg': '1',
		'thalach': '149',
		'exang': '0',
		'oldpeak': '0.3',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '35',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '120',
		'chol': '198',
		'fbs': '0',
		'restecg': '1',
		'thalach': '130',
		'exang': '1',
		'oldpeak': '1.6',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '57',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '150',
		'chol': '276',
		'fbs': '0',
		'restecg': '0',
		'thalach': '112',
		'exang': '1',
		'oldpeak': '0.6',
		'slope': '1',
		'ca': '1',
		'thal': '1'
	}],
	['0', {
		'age': '65',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '110',
		'chol': '248',
		'fbs': '0',
		'restecg': '0',
		'thalach': '158',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '2',
		'ca': '2',
		'thal': '1'
	}],
	['1', {
		'age': '54',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '132',
		'chol': '288',
		'fbs': '1',
		'restecg': '0',
		'thalach': '159',
		'exang': '1',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '52',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '108',
		'chol': '233',
		'fbs': '1',
		'restecg': '1',
		'thalach': '147',
		'exang': '0',
		'oldpeak': '0.1',
		'slope': '2',
		'ca': '3',
		'thal': '3'
	}],
	['1', {
		'age': '50',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '129',
		'chol': '196',
		'fbs': '0',
		'restecg': '1',
		'thalach': '163',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '48',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '130',
		'chol': '245',
		'fbs': '0',
		'restecg': '0',
		'thalach': '180',
		'exang': '0',
		'oldpeak': '0.2',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '43',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '110',
		'chol': '211',
		'fbs': '0',
		'restecg': '1',
		'thalach': '161',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '35',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '138',
		'chol': '183',
		'fbs': '0',
		'restecg': '1',
		'thalach': '182',
		'exang': '0',
		'oldpeak': '1.4',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '63',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '145',
		'chol': '233',
		'fbs': '1',
		'restecg': '0',
		'thalach': '150',
		'exang': '0',
		'oldpeak': '2.3',
		'slope': '0',
		'ca': '0',
		'thal': '1'
	}],
	['1', {
		'age': '41',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '135',
		'chol': '203',
		'fbs': '0',
		'restecg': '1',
		'thalach': '132',
		'exang': '0',
		'oldpeak': '0',
		'slope': '1',
		'ca': '0',
		'thal': '1'
	}],
	['0', {
		'age': '64',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '120',
		'chol': '246',
		'fbs': '0',
		'restecg': '0',
		'thalach': '96',
		'exang': '1',
		'oldpeak': '2.2',
		'slope': '0',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '53',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '142',
		'chol': '226',
		'fbs': '0',
		'restecg': '0',
		'thalach': '111',
		'exang': '1',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '54',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '160',
		'chol': '201',
		'fbs': '0',
		'restecg': '1',
		'thalach': '163',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '42',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '140',
		'chol': '226',
		'fbs': '0',
		'restecg': '1',
		'thalach': '178',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '52',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '118',
		'chol': '186',
		'fbs': '0',
		'restecg': '0',
		'thalach': '190',
		'exang': '0',
		'oldpeak': '0',
		'slope': '1',
		'ca': '0',
		'thal': '1'
	}],
	['1', {
		'age': '43',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '150',
		'chol': '247',
		'fbs': '0',
		'restecg': '1',
		'thalach': '171',
		'exang': '0',
		'oldpeak': '1.5',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '37',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '120',
		'chol': '215',
		'fbs': '0',
		'restecg': '1',
		'thalach': '170',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '68',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '144',
		'chol': '193',
		'fbs': '1',
		'restecg': '1',
		'thalach': '141',
		'exang': '0',
		'oldpeak': '3.4',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '57',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '132',
		'chol': '207',
		'fbs': '0',
		'restecg': '1',
		'thalach': '168',
		'exang': '1',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '64',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '140',
		'chol': '313',
		'fbs': '0',
		'restecg': '1',
		'thalach': '133',
		'exang': '0',
		'oldpeak': '0.2',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '37',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '130',
		'chol': '250',
		'fbs': '0',
		'restecg': '1',
		'thalach': '187',
		'exang': '0',
		'oldpeak': '3.5',
		'slope': '0',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '41',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '112',
		'chol': '250',
		'fbs': '0',
		'restecg': '1',
		'thalach': '179',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '64',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '170',
		'chol': '227',
		'fbs': '0',
		'restecg': '0',
		'thalach': '155',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '52',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '128',
		'chol': '204',
		'fbs': '1',
		'restecg': '1',
		'thalach': '156',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '0'
	}],
	['1', {
		'age': '47',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '130',
		'chol': '253',
		'fbs': '0',
		'restecg': '1',
		'thalach': '179',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '64',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '128',
		'chol': '263',
		'fbs': '0',
		'restecg': '1',
		'thalach': '105',
		'exang': '1',
		'oldpeak': '0.2',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '53',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '128',
		'chol': '216',
		'fbs': '0',
		'restecg': '0',
		'thalach': '115',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '0'
	}],
	['1', {
		'age': '58',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '140',
		'chol': '211',
		'fbs': '1',
		'restecg': '0',
		'thalach': '165',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '46',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '120',
		'chol': '249',
		'fbs': '0',
		'restecg': '0',
		'thalach': '144',
		'exang': '0',
		'oldpeak': '0.8',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '67',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '106',
		'chol': '223',
		'fbs': '0',
		'restecg': '1',
		'thalach': '142',
		'exang': '0',
		'oldpeak': '0.3',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '45',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '112',
		'chol': '160',
		'fbs': '0',
		'restecg': '1',
		'thalach': '138',
		'exang': '0',
		'oldpeak': '0',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '58',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '112',
		'chol': '230',
		'fbs': '0',
		'restecg': '0',
		'thalach': '165',
		'exang': '0',
		'oldpeak': '2.5',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '62',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '124',
		'chol': '209',
		'fbs': '0',
		'restecg': '1',
		'thalach': '163',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '55',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '132',
		'chol': '342',
		'fbs': '0',
		'restecg': '1',
		'thalach': '166',
		'exang': '0',
		'oldpeak': '1.2',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '68',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '118',
		'chol': '277',
		'fbs': '0',
		'restecg': '1',
		'thalach': '151',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '41',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '112',
		'chol': '268',
		'fbs': '0',
		'restecg': '0',
		'thalach': '172',
		'exang': '1',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '60',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '125',
		'chol': '258',
		'fbs': '0',
		'restecg': '0',
		'thalach': '141',
		'exang': '1',
		'oldpeak': '2.8',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '38',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '138',
		'chol': '175',
		'fbs': '0',
		'restecg': '1',
		'thalach': '173',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '4',
		'thal': '2'
	}],
	['1', {
		'age': '42',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '102',
		'chol': '265',
		'fbs': '0',
		'restecg': '0',
		'thalach': '122',
		'exang': '0',
		'oldpeak': '0.6',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '65',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '155',
		'chol': '269',
		'fbs': '0',
		'restecg': '1',
		'thalach': '148',
		'exang': '0',
		'oldpeak': '0.8',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '64',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '130',
		'chol': '303',
		'fbs': '0',
		'restecg': '1',
		'thalach': '122',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '39',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '140',
		'chol': '321',
		'fbs': '0',
		'restecg': '0',
		'thalach': '182',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '56',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '130',
		'chol': '221',
		'fbs': '0',
		'restecg': '0',
		'thalach': '163',
		'exang': '0',
		'oldpeak': '0',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
]