from moteur_id3.noeud_de_decision import NoeudDeDecision
from moteur_id3.id3 import ID3


# Les données d'apprentissage.
donnees = [
    ['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '1',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '3',
		'slope': '2',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '3',
		'slope': '0',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '4',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '1',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '3',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '3',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '3',
		'slope': '2',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '3',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '1',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '2',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '4',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '3',
		'chol': '1',
		'fbs': '1',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '1',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '3',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '4',
		'chol': '2',
		'fbs': '0',
		'restecg': '2',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '2',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '1',
		'fbs': '1',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '2',
		'thal': '2'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '3',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '1',
		'fbs': '1',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '1',
		'restecg': '0',
		'thalach': '1',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '2',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '1',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '1',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '3',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '1',
		'fbs': '1',
		'restecg': '1',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '1',
		'thal': '1'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '3',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '0',
		'ca': '0',
		'thal': '1'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '4',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '1',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '1',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '5',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '3',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '1',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '5',
		'slope': '0',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '3',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '4',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '3',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '1',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '1',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '3',
		'trestbps': '3',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '1',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '2',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '3',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['1', {
		'age': '4',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '4',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '4',
		'chol': '1',
		'fbs': '1',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '3',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '5',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '3',
		'slope': '0',
		'ca': '2',
		'thal': '3'
	}],
	['1', {
		'age': '1',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['1', {
		'age': '3',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '2',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '3',
		'slope': '0',
		'ca': '3',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '3',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '3',
		'slope': '1',
		'ca': '3',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '4',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['1', {
		'age': '4',
		'sex': '0' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '5',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '4',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '0',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '0' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '3',
		'thal': '2'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '1',
		'exang': '1',
		'oldpeak': '2',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '1',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '1',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '3',
		'trestbps': '2',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '2',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '4',
		'thal': '3'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '2',
		'ca': '2',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '3',
		'slope': '1',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '2',
		'chol': '2',
		'fbs': '1',
		'restecg': '0',
		'thalach': '3',
		'exang': '1',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '1'
	}],
	['0', {
		'age': '3',
		'sex': '0' ,
		'cp': '1',
		'trestbps': '2',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '1',
		'thal': '2'
	}],
	['0', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '2',
		'fbs': '0',
		'restecg': '0',
		'thalach': '2',
		'exang': '0',
		'oldpeak': '2',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '1',
		'chol': '2',
		'fbs': '1',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '0',
		'ca': '0',
		'thal': '3'
	}],
	['0', {
		'age': '3',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '1',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '2',
		'ca': '1',
		'thal': '3'
	}],
	['0', {
		'age': '4',
		'sex': '1' ,
		'cp': '2',
		'trestbps': '3',
		'chol': '1',
		'fbs': '0',
		'restecg': '0',
		'thalach': '3',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '3'
	}],
	['1', {
		'age': '2',
		'sex': '1' ,
		'cp': '0',
		'trestbps': '1',
		'chol': '2',
		'fbs': '0',
		'restecg': '1',
		'thalach': '4',
		'exang': '0',
		'oldpeak': '1',
		'slope': '1',
		'ca': '0',
		'thal': '2'
	}]
]

id3 = ID3()
arbre = id3.construit_arbre(donnees)
print('Arbre de décision :')
print(arbre)
print()

print('Exemplification :')
print(arbre.classifie({
        'age': 'midlife',
        'competition': 'no',
        'type': 'hardware'}))